export const launches = {
  REQUEST_LAUNCHES_REQUEST: 'ENTITIES/REQUEST_LAUNCHES_REQUEST',
  REQUEST_LAUNCHES_SUCCESS: 'ENTITIES/REQUEST_LAUNCHES_SUCCESS',
  REQUEST_LAUNCHES_ERROR: 'ENTITIES/REQUEST_LAUNCHES_ERROR'
}

export const todoList = {
  TODO_LIST_ADD_START: 'TODOS/TODO_LIST_ADD_START',
  TODO_LIST_ADD_SUCCESS: 'TODOS/TODO_LIST_ADD_SUCCESS',
  TODO_LIST_ADD_ERROR: 'TODOS/TODO_LIST_ADD_ERROR'
}

export const removeTodoList = {
  TODO_LIST_REMOVE_START: 'TODOS/TODO_LIST_REMOVE_START',
  TODO_LIST_REMOVE_SUCCESS: 'TODOS/TODO_LIST_REMOVE_SUCCESS',
  TODO_LIST_REMOVE_ERROR: 'TODOS/TODO_LIST_REMOVE_ERROR'
}

export const addTodo = {
  TODO_ADD_START: 'TODOS/TODO_ADD_TO_LIST_START',
  TODO_ADD_SUCCESS: 'TODOS/TODO_ADD_TO_LIST_SUCCESS',
  TODO_ADD_ERROR: 'TODOS/TODO_ADD_TO_LIST_ERROR'
}

export const removeTodo = {
  TODO_REMOVE_START: 'TODOS/TODO_REMOVE_START',
  TODO_REMOVE_SUCCESS: 'TODOS/TODO_REMOVE_SUCCESS',
  TODO_REMOVE_ERROR: 'TODOS/TODO_REMOVE_ERROR'
}

export const saveTodo = {
  TODO_SAVE_START: 'TODOS/TODO_SAVE_START',
  TODO_SAVE_SUCCESS: 'TODOS/TODO_SAVE_SUCCESS',
  TODO_SAVE_ERROR: 'TODOS/TODO_SAVE_ERROR'
}
