const types = {
  REQUEST_LAUNCHES: 'ENTITIES/REQUEST_LAUNCHES',
  REQUEST_LAUNCHES_SUCCESS: 'ENTITIES/REQUEST_LAUNCHES_SUCCESS',
  REQUEST_LAUNCHES_ERROR: 'ENTITIES/REQUEST_LAUNCHES_ERROR'
}

export default types