export const launches = {
  REQUEST_LAUNCHES_REQUEST: 'ENTITIES/REQUEST_LAUNCHES_REQUEST',
  REQUEST_LAUNCHES_SUCCESS: 'ENTITIES/REQUEST_LAUNCHES_SUCCESS',
  REQUEST_LAUNCHES_ERROR: 'ENTITIES/REQUEST_LAUNCHES_ERROR'
}